server:
  port: 80

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/se?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123123
    driver-class-name: com.mysql.cj.jdbc.Driver
